### ISSUE TITLE
while training on mb dataset, err will be nan

### ISSUE THREAD

**Issue by Sarah20187** [amitshaked/resmatch#1]
After preparing data, I use  `th main.lua -ds mb -a train_mcn -mc mc-cnn -m slow -gpu 2` to train a matching cost net and error occurred.
```
===> Loading matching cost network...
5
===> Loaded! Network: mb_mc-cnn_slow_LL_rgb
===> training matching cost network
{[........................................ 2/402508 ....................................]  ETA: 1D8h | Step: 289ms
  1 : nan
}
2
WARNING! err=nan

```
Could you help me?

**Comment by amitshaked** [comment]
Thanks for bringing up the issue. It's working now. Please make sure that after you compile the MiddEval3-SDK for Middlebury dataset, you end up with the computemask binary in one of the directories listed in your PATH enviromential variable.

**Comment by Sarah20187** [comment]
hi,
  Thank you for your reply. after I applied your modified code, the problem
remains randomly.
 I'm sure that the mask file is correct as it works while I train mb slow
net on mc-cnn source code? Have you figure out what leads the nan error?


2017-01-20 20:36 GMT+01:00 amitshaked <notifications@github.com>:
