### ISSUE TITLE
storage/data.kitti.rgb/x0.t7 is not specified?

### ISSUE THREAD

**Issue by sjkai** [amitshaked/resmatch#4]
When I run the preprocessing script:
    `scripts/preprocess_kitti.lua -color rgb -storage storage`
There is an error:

>.......
383
384
385
386
387
388
389
luajit: cannot open <storage/data.kitti.rgb/x0.t7> in mode  w at /home/jack/torch/pkg/torch/lib/TH/THDiskFile.c:670
stack traceback:
	[C]: at 0x7f0091583360
	[C]: in function 'DiskFile'
	/home/jack/torch/install/share/lua/5.1/torch/File.lua:385: in function 'save'
	scripts/preprocess_kitti.lua:144: in main chunk
	[C]: at 0x00406670 

The README.md file doesn't specify the file needed in `storage/data.kitti.rgb/x0.t7`
Where can I find the required data? Thank you!

**Comment by amitshaked** [comment]
The preprocess script creates it. Do you have a storage directory (named "storage") inside the main directory?

**Comment by sjkai** [comment]
Yes, Thank you. The problem has been solved.
